services:
  - type: web
    name: taskease
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGHOST
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGPORT
        sync: false
      - key: PGUSER
        sync: false
      - key: BEDROCK_TENANT_ID
        value: orange-z6csqjyyt3
      - key: BEDROCK_SUBSCRIPTION_KEY
        value: 267ddd32dcf04cc48d4927bea67423eb