services:
  - type: web
    name: taskease
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: taskease-db
          property: connectionString
      - key: NODE_ENV
        value: production

databases:
  - name: taskease-db
    databaseName: taskease
    user: taskease_user